INSERT INTO desk_user (username) VALUES ('Maha'); 
INSERT INTO desk_user (username) VALUES ('Sam'); 
INSERT INTO desk_user (username) VALUES ('Pablo');
INSERT INTO desk_user (username) VALUES ('Adeola');
INSERT INTO desk_user (username) VALUES ('Megumi'); 
INSERT INTO desk_user (username) VALUES ('Serena');
INSERT INTO desk_user (username) VALUES ('Ali');
INSERT INTO desk (desk_name) VALUES ('desk 1');
INSERT INTO desk (desk_name) VALUES ('desk 2');
INSERT INTO desk (desk_name) VALUES ('desk 3');
INSERT INTO desk (desk_name) VALUES ('desk 4');
INSERT INTO desk (desk_name) VALUES ('desk 5');
INSERT INTO desk (desk_name) VALUES ('desk 6');
INSERT INTO booking (desk_user_id, booking_date) VALUES (1,'2022-01-17'); 
INSERT INTO booking (desk_user_id, booking_date) VALUES (2,'2022-01-19');
INSERT INTO booking (desk_user_id, booking_date) VALUES (1,'2022-01-19');
INSERT INTO booking (desk_user_id, booking_date) VALUES (3,'2022-01-19');
INSERT INTO booking (desk_user_id, booking_date) VALUES (3,'2022-01-20');
INSERT INTO booking (desk_user_id, booking_date) VALUES (1,'2022-01-20');
INSERT INTO booking (desk_user_id, booking_date) VALUES (1,'2022-01-21');
INSERT INTO booking (desk_user_id, desk_id, booking_date) VALUES (4,1,'2022-01-20');
INSERT INTO booking (desk_user_id, desk_id, booking_date) VALUES (5,3,'2022-01-18');
INSERT INTO booking (desk_user_id, desk_id, booking_date) VALUES (5,3,'2022-01-20');
INSERT INTO booking (desk_user_id, desk_id, booking_date) VALUES (5,3,'2022-01-21');
INSERT INTO booking (desk_user_id, desk_id, booking_date) VALUES (6,4,'2022-01-19');
INSERT INTO booking (desk_user_id, desk_id, booking_date) VALUES (6,5,'2022-01-20');
INSERT INTO booking (desk_user_id, desk_id, booking_date) VALUES (7,6,'2022-01-19');
INSERT INTO booking (desk_user_id, desk_id, booking_date) VALUES (7,6,'2022-01-21');
INSERT INTO booking (desk_user_id, desk_id, booking_date) VALUES (3,4,'2022-01-21');